name: Build deb file
on: [ pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/checkout@v2
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pyqt5 python3-pip curl
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller pyqt5-plugins requests
      - name: Build
        run: |
          chmod +x packaging/ubuntu/build_deb.sh
          /bin/bash -c ./packaging/ubuntu/build_deb.sh
      - name: Upload deb file
        uses: actions/upload-artifact@v2.2.4
        with:
          name: "altserver-linuxgui.deb"
          path: "altserver-linuxgui.deb"
